default_platform(:ios)

platform :ios do
  before_all do 
    cocoapods(try_repo_update_on_error: true)
  end 

  desc "Build and run unit test"
  lane :test do
    scan(scheme: "BullsEye")
  end

  desc "Build and run UI test"
  lane :ui_test do
    scan(scheme: "UITests")
  end
end
